/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Indicator;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-03-29T15:47:54.662Z")

@Validated
@Api(value = "indicator", description = "the indicator API")
@RequestMapping(value = "/k043/gocycle/1.0.0")
public interface IndicatorApi {

    @ApiOperation(value = "Add a new indicator to the API", nickname = "addIndicator", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:indicators", description = "read your indicators"),
            @AuthorizationScope(scope = "write:indicators", description = "modify indicators in your account")
            })
    }, tags={ "indicator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/indicator",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addIndicator(@ApiParam(value = "Indicator object that needs to be added to the store" ,required=true )  @Valid @RequestBody Indicator body);


    @ApiOperation(value = "Deletes a indicator", nickname = "deleteIndicator", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:indicators", description = "read your indicators"),
            @AuthorizationScope(scope = "write:indicators", description = "modify indicators in your account")
            })
    }, tags={ "indicator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Indicator not found") })
    @RequestMapping(value = "/indicator/{indicatorId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteIndicator(@ApiParam(value = "Indicator id to delete",required=true) @PathVariable("indicatorId") Long indicatorId,@ApiParam(value = "" ) @RequestHeader(value="api_key", required=false) String apiKey);


    @ApiOperation(value = "Find indicator by ID", nickname = "getIndicatorById", notes = "Returns a single indicator", response = Indicator.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "indicator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Indicator.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Indicator not found") })
    @RequestMapping(value = "/indicator/{indicatorId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<Indicator> getIndicatorById(@ApiParam(value = "ID of indicator to return",required=true) @PathVariable("indicatorId") Long indicatorId);


    @ApiOperation(value = "Update an existing indicator", nickname = "updateIndicator", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:indicators", description = "read your indicators"),
            @AuthorizationScope(scope = "write:indicators", description = "modify indicators in your account")
            })
    }, tags={ "indicator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Indicator not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/indicator",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateIndicator(@ApiParam(value = "Indicator object that needs to be added" ,required=true )  @Valid @RequestBody Indicator body);


    @ApiOperation(value = "Updates a indicator in the store with form data", nickname = "updateIndicatorWithForm", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:indicators", description = "read your indicators"),
            @AuthorizationScope(scope = "write:indicators", description = "modify indicators in your account")
            })
    }, tags={ "indicator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/indicator/{indicatorId}",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.POST)
    ResponseEntity<Void> updateIndicatorWithForm(@ApiParam(value = "ID of indicator that needs to be updated",required=true) @PathVariable("indicatorId") Long indicatorId,@ApiParam(value = "Updated name of the indicator") @RequestParam(value="name", required=false)  String name,@ApiParam(value = "Updated status of the indicator") @RequestParam(value="status", required=false)  String status);

}
