/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Transport;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-03-29T15:47:54.662Z")

@Validated
@Api(value = "transport", description = "the transport API")
@RequestMapping(value = "/k043/gocycle/1.0.0")
public interface TransportApi {

    @ApiOperation(value = "Add a new transport to the API", nickname = "addTransport", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:transports", description = "read your indicators"),
            @AuthorizationScope(scope = "write:transports", description = "modify indicators in your account")
            })
    }, tags={ "transport", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/transport",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addTransport(@ApiParam(value = "Transport object that needs to be added to the store" ,required=true )  @Valid @RequestBody Transport body);


    @ApiOperation(value = "Deletes a transport", nickname = "deleteTransport", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:transports", description = "read your indicators"),
            @AuthorizationScope(scope = "write:transports", description = "modify indicators in your account")
            })
    }, tags={ "transport", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Transport not found") })
    @RequestMapping(value = "/transport/{transportId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTransport(@ApiParam(value = "Transport id to delete",required=true) @PathVariable("transportId") Long transportId,@ApiParam(value = "" ) @RequestHeader(value="api_key", required=false) String apiKey);


    @ApiOperation(value = "Find transport by ID", nickname = "getTransportById", notes = "Returns a single transport", response = Transport.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "transport", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Transport.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Transport not found") })
    @RequestMapping(value = "/transport/{transportId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<Transport> getTransportById(@ApiParam(value = "ID of transport to return",required=true) @PathVariable("transportId") Long transportId);


    @ApiOperation(value = "Update an existing transport", nickname = "updateTransport", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:transports", description = "read your indicators"),
            @AuthorizationScope(scope = "write:transports", description = "modify indicators in your account")
            })
    }, tags={ "transport", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Transport not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/transport",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateTransport(@ApiParam(value = "Transport object that needs to be added" ,required=true )  @Valid @RequestBody Transport body);


    @ApiOperation(value = "Updates a transport in the store with form data", nickname = "updateTransportWithForm", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:transports", description = "read your indicators"),
            @AuthorizationScope(scope = "write:transports", description = "modify indicators in your account")
            })
    }, tags={ "transport", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/transport/{transportId}",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.POST)
    ResponseEntity<Void> updateTransportWithForm(@ApiParam(value = "ID of transport that needs to be updated",required=true) @PathVariable("transportId") Long transportId,@ApiParam(value = "Updated name of the transport") @RequestParam(value="name", required=false)  String name,@ApiParam(value = "Updated status of the transport") @RequestParam(value="status", required=false)  String status);

}
