/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Trip;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-03-29T15:47:54.662Z")

@Validated
@Api(value = "trip", description = "the trip API")
@RequestMapping(value = "/k043/gocycle/1.0.0")
public interface TripApi {

    @ApiOperation(value = "Add a new trip to the API", nickname = "addTrip", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:trips", description = "modify indicators in your account"),
            @AuthorizationScope(scope = "read:trips", description = "read your indicators")
            })
    }, tags={ "trip", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/trip",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addTrip(@ApiParam(value = "Trip object that needs to be added to the store" ,required=true )  @Valid @RequestBody Trip body);


    @ApiOperation(value = "Deletes a trip", nickname = "deleteTrip", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:trips", description = "modify indicators in your account"),
            @AuthorizationScope(scope = "read:trips", description = "read your indicators")
            })
    }, tags={ "trip", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Trip not found") })
    @RequestMapping(value = "/trip/{tripId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTrip(@ApiParam(value = "Trip id to delete",required=true) @PathVariable("tripId") Long tripId,@ApiParam(value = "" ) @RequestHeader(value="api_key", required=false) String apiKey);


    @ApiOperation(value = "Find trip by ID", nickname = "getTripById", notes = "Returns a single trip", response = Trip.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "trip", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Trip.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Trip not found") })
    @RequestMapping(value = "/trip/{tripId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<Trip> getTripById(@ApiParam(value = "ID of trip to return",required=true) @PathVariable("tripId") Long tripId);


    @ApiOperation(value = "Update an existing trip", nickname = "updateTrip", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:trips", description = "modify indicators in your account"),
            @AuthorizationScope(scope = "read:trips", description = "read your indicators")
            })
    }, tags={ "trip", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Trip not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/trip",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateTrip(@ApiParam(value = "Trip object that needs to be added" ,required=true )  @Valid @RequestBody Trip body);


    @ApiOperation(value = "Updates a trip in the store with form data", nickname = "updateTripWithForm", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:trips", description = "modify indicators in your account"),
            @AuthorizationScope(scope = "read:trips", description = "read your indicators")
            })
    }, tags={ "trip", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/trip/{tripId}",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.POST)
    ResponseEntity<Void> updateTripWithForm(@ApiParam(value = "ID of trip that needs to be updated",required=true) @PathVariable("tripId") Long tripId,@ApiParam(value = "Updated name of the trip") @RequestParam(value="name", required=false)  String name,@ApiParam(value = "Updated status of the trip") @RequestParam(value="status", required=false)  String status);

}
