/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.TripIndicator;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-03-29T15:47:54.662Z")

@Validated
@Api(value = "trip_indicator", description = "the trip_indicator API")
@RequestMapping(value = "/k043/gocycle/1.0.0")
public interface TripIndicatorApi {

    @ApiOperation(value = "Add a new trip_indicator to the API", nickname = "addTripindicator", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:trip_indicators", description = "modify indicators in your account"),
            @AuthorizationScope(scope = "read:trip_indicators", description = "read your indicators")
            })
    }, tags={ "trip_indicator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/trip_indicator",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addTripindicator(@ApiParam(value = "Trip_indicator object that needs to be added to the store" ,required=true )  @Valid @RequestBody TripIndicator body);


    @ApiOperation(value = "Deletes a trip_indicator", nickname = "deleteTripIndicator", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:trip_indicators", description = "modify indicators in your account"),
            @AuthorizationScope(scope = "read:trip_indicators", description = "read your indicators")
            })
    }, tags={ "trip_indicator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Trip_indicator not found") })
    @RequestMapping(value = "/trip_indicator/{trip_indicatorId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTripIndicator(@ApiParam(value = "Trip_indicator id to delete",required=true) @PathVariable("trip_indicatorId") Long tripIndicatorId,@ApiParam(value = "" ) @RequestHeader(value="api_key", required=false) String apiKey);


    @ApiOperation(value = "Find trip_indicator by ID", nickname = "getTripindicatorById", notes = "Returns a single trip_indicator", response = TripIndicator.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "trip_indicator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TripIndicator.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Trip_indicator not found") })
    @RequestMapping(value = "/trip_indicator/{trip_indicatorId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<TripIndicator> getTripindicatorById(@ApiParam(value = "ID of trip_indicator to return",required=true) @PathVariable("trip_indicatorId") Long tripIndicatorId);


    @ApiOperation(value = "Updates a trip_indicator in the store with form data", nickname = "updateTripIndicatorWithForm", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:trip_indicators", description = "modify indicators in your account"),
            @AuthorizationScope(scope = "read:trip_indicators", description = "read your indicators")
            })
    }, tags={ "trip_indicator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/trip_indicator/{trip_indicatorId}",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.POST)
    ResponseEntity<Void> updateTripIndicatorWithForm(@ApiParam(value = "ID of trip_indicator that needs to be updated",required=true) @PathVariable("trip_indicatorId") Long tripIndicatorId,@ApiParam(value = "Updated name of the trip_indicator") @RequestParam(value="name", required=false)  String name,@ApiParam(value = "Updated status of the trip_indicator") @RequestParam(value="status", required=false)  String status);


    @ApiOperation(value = "Update an existing trip_indicator", nickname = "updateTripindicator", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:trip_indicators", description = "modify indicators in your account"),
            @AuthorizationScope(scope = "read:trip_indicators", description = "read your indicators")
            })
    }, tags={ "trip_indicator", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Trip_indicator not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/trip_indicator",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateTripindicator(@ApiParam(value = "Trip_indicator object that needs to be added" ,required=true )  @Valid @RequestBody TripIndicator body);

}
