/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.26).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.TripRoad;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-03-29T15:47:54.662Z")

@Validated
@Api(value = "trip_road", description = "the trip_road API")
@RequestMapping(value = "/k043/gocycle/1.0.0")
public interface TripRoadApi {

    @ApiOperation(value = "Add a new trip_road to the API", nickname = "addTripRoad", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:trip_roads", description = "read your indicators"),
            @AuthorizationScope(scope = "write:trip_roads", description = "modify indicators in your account")
            })
    }, tags={ "trip_road", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/trip_road",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addTripRoad(@ApiParam(value = "Trip_road object that needs to be added to the store" ,required=true )  @Valid @RequestBody TripRoad body);


    @ApiOperation(value = "Deletes a trip_road", nickname = "deleteTripRoad", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:trip_roads", description = "read your indicators"),
            @AuthorizationScope(scope = "write:trip_roads", description = "modify indicators in your account")
            })
    }, tags={ "trip_road", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Trip_road not found") })
    @RequestMapping(value = "/trip_road/{trip_roadId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTripRoad(@ApiParam(value = "Trip_road id to delete",required=true) @PathVariable("trip_roadId") Long tripRoadId,@ApiParam(value = "" ) @RequestHeader(value="api_key", required=false) String apiKey);


    @ApiOperation(value = "Find trip_road by ID", nickname = "getTripRoadById", notes = "Returns a single trip_road", response = TripRoad.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "trip_road", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TripRoad.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Trip_road not found") })
    @RequestMapping(value = "/trip_road/{trip_roadId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<TripRoad> getTripRoadById(@ApiParam(value = "ID of trip_road to return",required=true) @PathVariable("trip_roadId") Long tripRoadId);


    @ApiOperation(value = "Update an existing trip_road", nickname = "updateTripRoad", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:trip_roads", description = "read your indicators"),
            @AuthorizationScope(scope = "write:trip_roads", description = "modify indicators in your account")
            })
    }, tags={ "trip_road", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Trip_road not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/trip_road",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updateTripRoad(@ApiParam(value = "Trip_road object that needs to be added" ,required=true )  @Valid @RequestBody TripRoad body);


    @ApiOperation(value = "Updates a trip_road in the store with form data", nickname = "updateTripRoadWithForm", notes = "", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "read:trip_roads", description = "read your indicators"),
            @AuthorizationScope(scope = "write:trip_roads", description = "modify indicators in your account")
            })
    }, tags={ "trip_road", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/trip_road/{trip_roadId}",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.POST)
    ResponseEntity<Void> updateTripRoadWithForm(@ApiParam(value = "ID of trip_road that needs to be updated",required=true) @PathVariable("trip_roadId") Long tripRoadId,@ApiParam(value = "Updated name of the trip_road") @RequestParam(value="name", required=false)  String name,@ApiParam(value = "Updated status of the trip_road") @RequestParam(value="status", required=false)  String status);

}
